Repository ros2/rosidl_typesupport_connext, pull requests merged in 2018-11, with the labels that each got.

#14 rename dynamic array to sequence
  rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em
Labels: in review

#13 Allow generated IDL files
  rosidl_typesupport_connext_c/cmake/rosidl_typesupport_connext_c_generate_interfaces.cmake
  rosidl_typesupport_connext_cpp/cmake/rosidl_typesupport_connext_cpp_generate_interfaces.cmake
Labels: in progress

#16 use uint8
  rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_connext_cpp/CMakeLists.txt
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/connext_static_cdr_stream.hpp
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/message_type_support.h
  rosidl_typesupport_connext_cpp/package.xml
  rosidl_typesupport_connext_cpp/resource/msg__type_support.cpp.em
Labels: in progress

#17 reduce verbosity when Connext is not available
  connext_cmake_module/CMakeLists.txt
  rosidl_typesupport_connext_c/CMakeLists.txt
  rosidl_typesupport_connext_cpp/CMakeLists.txt
Labels: enhancement, in review
