Repository ros2/rosidl_typesupport_connext, pull requests merged in 2019-05, with the labels that each got.

#30 Add cpplint flag to ignore long functions in generated code
  rosidl_typesupport_connext_c/cmake/rosidl_typesupport_connext_c_generate_interfaces.cmake
  rosidl_typesupport_connext_cpp/cmake/rosidl_typesupport_connext_cpp_generate_interfaces.cmake
Labels: in progress

#29 add WString support
  rosidl_typesupport_connext_c/CMakeLists.txt
  rosidl_typesupport_connext_c/include/rosidl_typesupport_connext_c/wstring_conversion.hpp
  rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_connext_c/src/wstring_conversion.cpp
  rosidl_typesupport_connext_cpp/CMakeLists.txt
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/wstring_conversion.hpp
  rosidl_typesupport_connext_cpp/resource/msg__type_support.cpp.em
  rosidl_typesupport_connext_cpp/src/wstring_conversion.cpp
Labels: enhancement, in review

#31 fix clang ignores
  rosidl_typesupport_connext_cpp/src/wstring_conversion.cpp
Labels: in review

#32 Combine package name with namespace in type support struct
  rosidl_typesupport_connext_c/resource/msg__type_support_c.cpp.em
  rosidl_typesupport_connext_c/resource/srv__type_support_c.cpp.em
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/message_type_support.h
  rosidl_typesupport_connext_cpp/include/rosidl_typesupport_connext_cpp/service_type_support.h
  rosidl_typesupport_connext_cpp/resource/msg__type_support.cpp.em
  rosidl_typesupport_connext_cpp/resource/srv__type_support.cpp.em
Labels: in review

#28 Generalize string matching for OSX Connext library in cmake module
  connext_cmake_module/cmake/Modules/FindConnext.cmake
Labels: in review
